### ISSUE TITLE
Commands from configuration

### ISSUE THREAD

**Issue by pdonorio** [rapydo/issues#15] opened 2017-05-31 13:32 UTC
There should be a YAML to be read from the core and from vanilla
to add custom commands to `rapydo-controller`.

Those commands are just some `exec` with `docker-compose` on running services.

A proposal:
```yaml

mycom:
  display_name: letsencrypt
  service: proxy
  command: updatecertificates
  user: root

```

**Comment by pdonorio** [comment] 2017-06-07 04:20
Reorganized the `shell` method in the app to be re-executed.

We decided to apply it in two different ways:

1. A base "container_exec" command should stay in the main YAML list and be treated as necessary
2. A list of custom commands will be handled with the `custom` subcommand of do

**Comment by pdonorio** [comment] 2017-06-07 05:56
This is completed on my side.
The controller `0.1.7` is the new release with custom commands.

See an example of custom configuration in [eudat](https://github.com/EUDAT-B2STAGE/http-api/blob/0.4.1/specs/project_configuration.yaml#L7-L13)

@mdantonio could you test it?

**Comment by mdantonio** [comment] 2017-06-08 11:45
It works well... but do not solve any of my use cases

First use case (already discussed): a customized "rapydo init" procedure (i.e. commands executed on the host machine, not on a container)

Second use case (not yet discussed): installation of bower libraries ( #17 )... this is a command to be executed on a NON running container

We already discussed about the first use case: clearly we need to attach the command to a custom function, it requires some piece of python put somewhere

But how could we solve the second use case?

**Comment by pdonorio** [comment] 2017-06-08 13:35
> Second use case (not yet discussed): installation of bower libraries ( #17 )... this is a command to be executed on a NON running container

This is similar to a one shot run of the rest client, see [this](https://github.com/rapydo/do/blob/master/rapydo/do/app.py#L495-L514). We may make a separated configuration for this `run` command (opposed to `up`)

**Comment by pdonorio** [comment] 2017-06-14 14:29
The `interfaces` command now follow this second use case.
So this can be easily hacked to do similar things for you.

**Comment by pdonorio** [comment] 2017-06-14 14:30
> We already discussed about the first use case: clearly we need to attach the command to a custom function, it requires some piece of python put somewhere

Can we create an issue for this, or is it already there?

**Comment by mdantonio** [comment] 2017-06-15 05:19
> Can we create an issue for this, or is it already there?

About inizialization (and custom inizialization) we have issue #8

**Comment by mdantonio** [comment] 2017-06-21 09:09
The letsencrypt command do not work for several issues:

**Problem**: the system looks for `self._ssl-certificate` function but it is implemented as `self._ssl_certificate`

**Solution**: I added a replace of - into _ when determining for function name

----------------

**Problem**: `current_method_name = inspect.currentframe().f_code.co_name` returns _ssl_certificate but ssl-certificate is expected. So the following `meta.pop('name') == 'letsencrypt'` fails since the meta is empty

**Temporary solution**: I forced `current_method_name = "ssl-certificate"`

----------------

**Banal problem**: the _ssl_certificate calls `self.shell()` and this function do not exist

**Banal solution**: changed `self.shell()` with `self._shell()`

----------------

**Problem**: the self._shell() is intended to execute a command on a running container:
```
2017-06-21 11:06:11,737 INFO    @rapydo.do.app Command request: PROXY(updatecertificates+[])
2017-06-21 11:06:11,858 INFO    @rapydo.do.compose Requesting within compose: 'exec_command'
2017-06-21 11:06:11,861 EXIT    @rapydo.do.compose Failed command execution:
No container found for proxy_1
```
**Solution**: no solution implement. We should use something like the _interfaces method, but we have to generalize it

**Comment by mdantonio** [comment] 2017-06-22 09:18
> Problem: the self._shell() is intended to execute a command on a running container:

Yesterday i was a bit tired... today the situation is clearer: the problem is not the one described... to execute the ssl-certificate command the proxy container MUST be running, so the use of ._shell is not wrong

This problem does not exist

However i re-tried the command with a running proxy and still the command does not work:

```
rapydo ssl-certificate
2017-06-22 09:13:20,444 INFO    @rapydo.do.app Do request: ssl-certificate
[...]
2017-06-22 09:13:23,831 INFO    @rapydo.do.app Command request: PROXY(updatecertificates+[])
2017-06-22 09:13:23,948 INFO    @rapydo.do.compose Requesting within compose: 'exec_command'
rpc error: code = 2 desc = oci runtime error: exec failed: container_linux.go:247: starting container process caused "exec format error"
```

The generalization of _interfaces command is still required for bower, I try to work on that just now

**Comment by pdonorio** [comment] 2017-06-22 09:54
`starting container process caused "exec format error"` usually means the command created for docker or docker compose is not compliant.

In your case `updatecertificates` is probably defined in `bashrc` which is not loaded by docker before the execution. 

I usually solve this kind of issue with `/bin/bash -c 'updatecertificates'` but we should find a better solution by going deeper into the problem...

**Comment by mdantonio** [comment] 2017-06-22 10:20
> but we should find a better solution by going deeper into the problem...

I agree. We will discuss that the next week.

> The generalization of _interfaces command is still required for bower, I try to work on that just now

It is done. More details in #17

**Comment by mdantonio** [comment] 2017-07-24 10:28
i should create a custom command for IMC... the problem is that this command should also take a couple of parameter. We are unable to create commands with parameters?

This snippet should work (to be added in project_configuration) but without parameters:

```
controller:
    commands:
        user_add:
            description: Create a new user on FTP
            service: ftp
            command: pure-pw useradd [EMAIL] -f /etc/pure-ftpd/passwd/pureftpd.passwd -m -u ftpuser -d /home/ftpusers/[USER_HOME]

```

**Comment by pdonorio** [comment] 2017-07-24 12:43
> I'm wrong or we are unable to create custom commands with parameters?

I have no idea, it might be true.

**Comment by pdonorio** [comment] 2017-08-01 09:40
If we refactor the commands in `app.py` to be based on a `Command` class (is there an issue for that?) we can implement commands inside each projects like this:

```bash
$ tree projects/MYPROJECT/commands

├── __init__.py
└── mycom.py
```

**Comment by mdantonio** [comment] 2017-08-02 05:36
> based on a Command class (is there an issue for that?)
Not yet

We should also open an issue to track the possibile migration from argparse to click

**Comment by pdonorio** [comment] 2017-08-02 05:56
> We should also open an issue to track the possibile migration from argparse to click

uhm, I smell a "last refactor" again 🤣  #56

**Comment by pdonorio** [comment] 2017-08-27 14:38
If #56 will be implemented then we are some steps closer to this to be solved. 

In fact I've discovered recently that there's another tool similar to our concept of "controller" which in a more generic way gives you a command to "manage" your project. The tool is called `manage`, reads a `YAML` and uses `click` as argparser. 

Finally - and that is what's really interesting for us - it uses click + YAML to allow custom commands: https://github.com/rochacbruno/manage#custom-commands

**Comment by mdantonio** [comment] 2017-08-28 05:10
Awesome!

And we can integrate this `manage` and maintain rapydo as name? (as done with invoke)

Something like this:

/bin/rapydo -> manage -> click -> rapydo-controller-stuffs

**Comment by pdonorio** [comment] 2017-08-28 05:58
> we can integrate this manage and maintain rapydo as name

Yes I think it's possible but we have to patiently create a prototype 😉

**Comment by mdantonio** [comment] 2017-12-22 06:51
The point here is: how to add custom commands in controller (commands able to perform operations on host machine => some python code written somewhere).
Custom commands implemented from configuration simply launch something on a running container and are not able to perform operations on the host machine

For example IMC could benefit of a command like:

rapydo fhg --pwd abc

to install FHG tools by providing the required password (now this task is performed by executing a bash script)


If we think that in a future we will be able to work on this we can keep open... but to be honest i think that we could close this issue (and also close the porting to click #56) due to a chronic lack of effort

**Comment by mdantonio** [comment] 2017-12-22 06:58
This last task is also reported in issue #27 => we can close this issue

**Closed by mdantonio** 2017-12-22 06:58 UTC
